version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
    time: "04:00"
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: puppeteer
    versions:
    - 6.0.0
    - 7.0.0
    - 7.0.1
    - 7.0.4
    - 7.1.0
    - 8.0.0
    - 9.0.0
  - dependency-name: bl
    versions:
    - 4.0.3
    - 4.0.4
    - 4.1.0
  - dependency-name: chrono-node
    versions:
    - 2.2.0
    - 2.2.1
    - 2.2.3
    - 2.2.4
    - 2.2.5
    - 2.2.6
  - dependency-name: "@influxdata/influxdb-client"
    versions:
    - 1.10.0
    - 1.11.0
    - 1.12.0
