{
 "title": "Whatsapp Tracking POC",
 "tags": [ "POC" ],
 "time": { "from": "now-6h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Status Available",
   "type": "graph",
   "gridPos": { "h": 6, "w": 13, "x": 0, "y": 0 },
   "yaxes": [
    { "format": "none", "label": "True/False" }
   ],
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\n\nRawSeries = from(bucket: \"whatsapp-tracking\")\n  |> range($range)\n  |> filter(fn:(r) => \n    r._measurement == \"status\" and \n    r._field  == \"statusAvailable\"\n  )\n  |> limit(n:1000)\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.contactName}))\n    |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()"
    }
   ]
  },
  {
   "title": "Activity",
   "type": "petrslavotinek-carpetplot-panel",
   "gridPos": { "h": 6, "w": 5, "x": 13, "y": 0 },
   "targets": [
    {
     "aggregation": "Last",
     "decimals": 2,
     "displayAliasType": "Warning / Critical",
     "displayType": "Regular",
     "displayValueWithAlias": "Never",
     "query": "from(bucket: \"whatsapp-tracking\") \n  |> range($range)\n  |> filter(fn:(r) => \n    r._measurement == \"status\" and \n    r._field  == \"offlineSince\"\n  )\n  |> limit(n:1000)\n",
     "units": "none",
     "valueHandler": "Number Threshold"
    }
   ]
  },
  {
   "title": "Online Status",
   "type": "natel-discrete-panel",
   "gridPos": { "h": 8, "w": 18, "x": 0, "y": 6 },
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\n\nRawSeries = from(bucket: \"whatsapp-tracking\")\n  |> range($range)\n  |> filter(fn:(r) => \n    r._measurement == \"status\" and \n    r._field  == \"offlineSince\"\n  )\n  |> limit(n:1000)\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.contactName}))\n    |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()"
    }
   ]
  },
  {
   "title": "Offline since",
   "type": "graph",
   "gridPos": { "h": 9, "w": 18, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "s", "label": "offline since" }
   ],
   "targets": [
    {
     "query": "FinalOutput = [\"_field\", \"_time\", \"_value\"]\n\nRawSeries = from(bucket: \"whatsapp-tracking\")\n  |> range($range)\n  |> filter(fn:(r) => \n    r._measurement == \"status\" and \n    r._field  == \"offlineSince\"\n  )\n  |> limit(n:1000)\n\nNamedSeries = RawSeries\n    |> map(fn: (r) => ({_value:r._value, _time:r._time, _field: r.contactName}))\n    |> keep(columns:FinalOutput)\n\nNamedSeries |> yield()"
    }
   ]
  }
 ]
}